import type { Metadata } from "next";
import "./globals.css";

import Navbar from "@/components/navbar";


export const metadata: Metadata = {
  title: "Atmajo's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
