import type { Metadata } from "next";
import "./globals.css";

import Navbar from "@/components/navbar";
import MaxWidthWrapper from "@/wrapper/max-width-wrapper";

export const metadata: Metadata = {
  title: "Atmajo's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <MaxWidthWrapper>
          <Navbar />
          {children}
        </MaxWidthWrapper>
      </body>
    </html>
  );
}
